@echo off
title ProdMon - BI Dashboard
echo Iniciando o Servidor ProdMon Dashboard...
echo Verificando dependencias...
pip install -r requirements.txt
echo Inicializando interface web...
streamlit run app.py
pause
